### ISSUE TITLE
Unity version compatibility 

### ISSUE THREAD

**Issue by yosun** [voximplant/unity_sdk#15]
Which version of unity has this been tested to work with?

**Comment by grigoryvp** [comment]
Both video and audio SDK and Tutorial was checked against version 5.5 https://unity.voximplant.com/tutorials/video_call/

If you have any suggestions or issues feel free to ask them directly

**Comment by yosun** [comment]
Which subversion of 5.5? .0f3 or one of the patch versions?

https://unity3d.com/unity/qa/patch-releases
https://unity3d.com/get-unity/download/archive

**Comment by grigoryvp** [comment]
We just re-tested it against 5.5.3f1 and 5.6.0f3, everything works fine! Since our SDK uses only general-purpose Unity API it should be stable on minor updates. If you have any procedures in mind or want to reference any best practices for Unity development - feel free to inform us directly, we want to improve our SDK and are open for suggestions!

**Comment by niveuseverto** [comment]
Greetings.

Last update of SDK was re-tested against Unity 2017.3.1f1.
